// frameworks/react/workspace/src/views/View2.tsx
import "@finos/fdc3";
import React, { useEffect, useState } from 'react';
import logo from '../logo.svg';

function View2() {
	const [message, setMessage] = useState("");

	useEffect(() => {
		(async function () {
			if (window.fdc3) {
				await window.fdc3.addContextListener((context) => {
					setMessage(JSON.stringify(context, undefined, "  "));
				});
			} else {
				console.error("FDC3 is not available");
			}
		})();
	}, []);

	return (
		<div className="col fill gap20">
			<header className="row spread middle">
				<div className="col">
					<h1>OpenFin React View 2</h1>
					<h1 className="tag">React app view in an OpenFin workspace</h1>
				</div>
				<div className="row middle gap10">
					<img src={logo} alt="OpenFin" height="40px" />
				</div>
			</header>
			<main className="col gap10 left">
				<fieldset>
					<label htmlFor="message">Context Received</label>
					<pre id="message">{message}</pre>
				</fieldset>
				<button onClick={() => setMessage("")}>Clear</button>
			</main>
		</div>
	);
}

export default View2;

// frameworks/angular/workspace-next/src/app/view2/view2.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-view2',
  templateUrl: './view2.component.html',
  styleUrls: ['./view2.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
})
export class View2Component {}

<div class="col fill gap20">
  <header class="row spread middle">
    <div class="col">
      <h1>OpenFin Angular View 2</h1>
      <h1 class="tag">Angular app view in an OpenFin workspace</h1>
    </div>
    <div class="row middle gap10">
      <img src="../assets/logo.svg" alt="OpenFin" height="40px" />
    </div>
  </header>
  <main class="col gap10 left width-full">

    @if (message()) {
      <fieldset class="width-full">
        <label htmlFor="message">Context Received</label>
        <pre id="message" class="width-full" style="min-height:110px">{{ message() }}</pre>
      </fieldset>
      <button (click)="clearMessage()">Clear</button>
    }

  </main>
</div>
