// frameworks/angular/workspace-next/src/app/provider/provider.component.ts
import { ChangeDetectionStrategy, Component, inject, OnInit } from "@angular/core";
import { WorkspaceService } from "../services/workspace.service";

@Component({
	standalone: true,
	selector: "app-provider",
	templateUrl: "./provider.component.html",
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [WorkspaceService],
})
export class ProviderComponent implements OnInit {
	private workspaceService = inject(WorkspaceService);

	ngOnInit(): void {
		this.workspaceService.init();
	}
}

<h1>Provider</h1>
<p>This is the platform window, which initializes the platform.</p>
<p>The window would usually be hidden, you can make it hidden on startup by setting the platform.autoShow flag to false in the manifest.fin.json</p>

// frameworks/react/workspace-platform-starter/src/Provider.tsx
import { useOpenFin } from "./hooks/useOpenFin";

export function Provider() {
	useOpenFin();

	return (
		<main>
			<h3>HERE Core platform provider</h3>
			<p>
				The window would usually be hidden, you can make it hidden on startup by setting the
				platform.autoShow flag to false in the manifest.fin.json
			</p>
		</main>
	);
}
