// frameworks/react/container/src/views/View1.tsx
import React from 'react';
import logo from '../logo.svg';
import * as Notifications from "@openfin/workspace/notifications";
import "@finos/fdc3";

function View1() {
	async function showNotification() {
		await Notifications.create({
			title: "Simple Notification",
			body: "This is a simple notification",
			toast: "transient",
			category: "default",
			template: "markdown"
		});
	}

	async function broadcastFDC3Context() {
		if (window.fdc3) {
			await window.fdc3.broadcast({
				type: 'fdc3.instrument',
				name: 'Microsoft Corporation',
				id: {
					ticker: 'MSFT'
				}
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	async function broadcastFDC3ContextAppChannel() {
		if (window.fdc3) {
			const appChannel = await window.fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");

			await appChannel.broadcast({
				type: 'fdc3.instrument',
				name: 'Apple Inc.',
				id: {
					ticker: 'AAPL'
				}
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	return (
		<div className="col fill gap20">
			<header className="row spread middle">
				<div className="col">
					<h1>OpenFin React View 1</h1>
					<h1 className="tag">React app view in an OpenFin container</h1>
				</div>
				<div className="row middle gap10">
					<img src={logo} alt="OpenFin" height="40px" />
				</div>
			</header>
			<main className="col gap10 left">
				<button onClick={() => showNotification()}>Show Notification</button>
				<button onClick={() => broadcastFDC3Context()}>Broadcast FDC3 Context</button>
				<button onClick={() => broadcastFDC3ContextAppChannel()}>Broadcast FDC3 Context on App Channel</button>
			</main>
		</div>
	);
}

export default View1;

// frameworks/angular/workspace-next/src/app/view1/view1.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { InteropService } from '../services/interop.service';
import { NotificationsService } from '../services/notifications.service';

@Component({
  standalone: true,
  selector: 'app-view1',
  templateUrl: './view1.component.html',
  styleUrls: ['./view1.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  providers: [NotificationsService, InteropService],
})
export class View1Component {
  private notificationService = inject(NotificationsService);
  private interopService = inject(InteropService);

  showNotification(): void {
    this.notificationService.create({
      title: 'Simple Notification',
      body: 'This is a simple notification',
      toast: 'transient',
      buttons: [
        {
          title: 'Click me',
        },
      ],
    });
  }

  broadcastFDC3Context(): void {
    this.interopService.broadcast({
      type: 'fdc3.instrument',
      name: 'Microsoft Corporation',
      id: {
        ticker: 'MSFT',
      },
    });
  }

  broadcastFDC3ContextAppChannel(): void {
    // if (window.fdc3) {
    //   const appChannel = await window.fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");
    //
    //   await appChannel.broadcast({
    //     type: 'fdc3.instrument',
    //     name: 'Apple Inc.',
    //     id: {
    //       ticker: 'AAPL'
    //     }
    //   });
    // } else {
    //   console.error("FDC3 is not available");
    // }
  }
}

<div class="col fill gap20">
  <header class="row spread middle">
    <div class="col">
      <h1>OpenFin Angular View 1</h1>
      <h1 class="tag">Angular app view in an OpenFin workspace</h1>
    </div>
    <div class="row middle gap10">
      <img src="../assets/logo.svg" alt="OpenFin" height="40px" />
    </div>
  </header>
  <main class="col gap10 left">
    <button (click)="showNotification()">Show Notification</button>
    <button (click)="broadcastFDC3Context()">Broadcast FDC3 Context</button>
<!--    <button (click)="broadcastFDC3ContextAppChannel()">Broadcast FDC3 Context on App Channel</button>-->
  </main>
</div>
