// frameworks/angular/container/src/app/view1/view1.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, type OnInit, signal } from "@angular/core";
import { addEventListener, create, register } from "@openfin/notifications";

@Component({
	selector: "app-view1",
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [CommonModule],
	template: `
		<div class="col fill gap20">
			<header class="row spread middle">
				<div class="col">
					<h1>HERE Angular View 1</h1>
					<h1 class="tag">Angular app view in an HERE container</h1>
				</div>
				<div class="row middle gap10">
					<img src="logo.svg" alt="HERE" height="40px" />
				</div>
			</header>
			<main class="col gap10 left">
				<button (click)="showNotification()">Show Notification</button>
				<button (click)="broadcastFDC3Context()">Broadcast FDC3 Context</button>
				<button (click)="broadcastFDC3ContextAppChannel()">
					Broadcast FDC3 Context on App Channel
				</button>
				<div>{{ notificationActionMessage() }}</div>
			</main>
		</div>
	`,
})
export class View1Component implements OnInit {
	notificationActionMessage = signal("");

	ngOnInit(): void {
		register().then(() => {
			addEventListener("notification-action", (event) => {
				console.log("Notification clicked:", event.result["customData"]);
				this.notificationActionMessage.set(event.result["customData"]);
			});
		});
	}

	showNotification(): void {
		create({
			platform: fin.me.identity.uuid,
			title: "Simple Notification",
			body: "This is a simple notification",
			toast: "transient",
			buttons: [
				{
					title: "Click me",
					type: "button",
					cta: true,
					onClick: {
						customData: "Notification action data",
					},
				},
			],
		});
	}

	broadcastFDC3Context() {
		if (fdc3) {
			fdc3.broadcast({
				type: "fdc3.instrument",
				name: "Microsoft Corporation",
				id: {
					ticker: "MSFT",
				},
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	async broadcastFDC3ContextAppChannel() {
		if (fdc3) {
			const appChannel = await fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");

			await appChannel.broadcast({
				type: "fdc3.instrument",
				name: "Apple Inc.",
				id: {
					ticker: "AAPL",
				},
			});
		} else {
			console.error("FDC3 is not available");
		}
	}
}

<div class="col fill gap20">
	<header class="row spread middle">
		<div class="col">
			<h1>OpenFin Angular View 1</h1>
			<h1 class="tag">Angular app view in an OpenFin container</h1>
		</div>
		<div class="row middle gap10">
			<img src="../../assets/logo.svg" alt="OpenFin" height="40px" />
		</div>
	</header>
	<main class="col gap10 left">
		<button (click)="showNotification()">Show Notification</button>
		<button (click)="broadcastFDC3Context()">Broadcast FDC3 Context</button>
		<button (click)="broadcastFDC3ContextAppChannel()">Broadcast FDC3 Context on App Channel</button>
	</main>
</div>

// frameworks/react/workspace/src/views/view1.tsx
import { useCallback } from "react";
import { type NotificationActionEvent } from "@openfin/notifications";
import { useNotifications } from "./hooks/useNotifications";
import { useFdc3Context } from "./hooks/useFdc3Context";
import { useFdc3Channel } from "./hooks/useFdc3Channel";

const CUSTOM_APP_CHANNEL = "CUSTOM-APP-CHANNEL";

export function View1() {
	const handleNotificationAction = useCallback((event: NotificationActionEvent) => {
		console.log("Notification clicked:", event.result?.["customData"]);
	}, []);

	const { create } = useNotifications(handleNotificationAction);
	const { broadcast: broadcastContext } = useFdc3Context();
	const { broadcast: broadcastChannel } = useFdc3Channel({ channelName: CUSTOM_APP_CHANNEL });

	const showNotification = () => {
		create({
			platform: fin.me.identity.uuid,
			title: "Simple Notification",
			body: "This is a simple notification",
			toast: "transient",
			buttons: [
				{
					title: "Click me",
					type: "button",
					cta: true,
					onClick: {
						customData: "Arbitrary custom data",
					},
				},
			],
		});
	};

	const broadcastFDC3Context = () => {
		broadcastContext({
			type: "fdc3.instrument",
			name: "Microsoft Corporation",
			id: {
				ticker: "MSFT",
			},
		});
	};

	const broadcastFDC3ContextAppChannel = () => {
		broadcastChannel({
			type: "fdc3.instrument",
			name: "Apple Inc.",
			id: {
				ticker: "AAPL",
			},
		});
	};

	return (
		<div className="col fill gap20">
			<header className="row spread middle">
				<div className="col">
					<h1>HERE React View 1</h1>
					<h1 className="tag">React app view in HERE Core</h1>
				</div>
				<div className="row middle gap10">
					<img src="logo.svg" alt="HERE" height="40px" />
				</div>
			</header>
			<main className="col gap10 left">
				<button type="button" onClick={showNotification}>
					Show Notification
				</button>
				<button type="button" onClick={broadcastFDC3Context}>
					Broadcast FDC3 Context
				</button>
				<button type="button" onClick={broadcastFDC3ContextAppChannel}>
					Broadcast FDC3 Context on App Channel
				</button>
			</main>
		</div>
	);
}
