// frameworks/angular/container/src/app/view2/view2.component.ts
import { ChangeDetectionStrategy, Component, type OnInit, signal } from "@angular/core";

@Component({
	selector: "app-view2",
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [],
	template: `
		<div class="col fill gap20">
			<header class="row spread middle">
				<div class="col">
					<h1>HERE Angular View 2</h1>
					<h1 class="tag">Angular app view in an HERE container</h1>
				</div>
				<div class="row middle gap10">
					<img src="logo.svg" alt="HERE" height="40px" />
				</div>
			</header>
			<main class="col gap10 left width-full">
				@if (message()) {
					<fieldset class="width-full">
						<label htmlFor="message">Context Received</label>
						<pre id="message" class="width-full" style="min-height: 110px">{{ message() }}</pre>
					</fieldset>
					<button (click)="clearMessage()">Clear</button>
				}
			</main>
		</div>
	`,
})
export class View2Component implements OnInit {
	message = signal<string>("");

	ngOnInit(): void {
		this.listenForFDC3Context();
		this.listenForFDC3ContextAppChannel();
	}

	listenForFDC3Context() {
		if (fdc3) {
			fdc3?.addContextListener("fdc3.instrument", (context) => {
				console.log("ContextService: received message", context);
				this.message.set(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	async listenForFDC3ContextAppChannel() {
		if (fdc3) {
			const appChannel = await fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");
			await appChannel.addContextListener((context) => {
				this.message.set(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	clearMessage() {
		this.message.set("");
	}
}

<div class="col fill gap20">
	<header class="row spread middle">
		<div class="col">
			<h1>OpenFin Angular View 2</h1>
			<h1 class="tag">Angular app view in an OpenFin container</h1>
		</div>
		<div class="row middle gap10">
			<img src="../../assets/logo.svg" alt="OpenFin" height="40px" />
		</div>
	</header>
	<main class="col gap10 left width-full">
		<fieldset class="width-full">
			<label htmlFor="message">Context Received</label>
			<pre id="message" class="width-full" style="min-height:110px">{{message}}</pre>
		</fieldset>
		<button (click)="message=''">Clear</button>
	</main>
</div>

// frameworks/react/workspace/src/views/view2.tsx
import { useCallback, useState } from "react";
import { type Context } from "@finos/fdc3";
import { useFdc3Context } from "./hooks/useFdc3Context";
import { useFdc3Channel } from "./hooks/useFdc3Channel";

const CUSTOM_APP_CHANNEL = "CUSTOM-APP-CHANNEL";

export function View2() {
	const [message, setMessage] = useState<string>("");

	const handleContext = useCallback((context: Context) => {
		setMessage(JSON.stringify(context, undefined, "  "));
	}, []);

	useFdc3Context({ contextType: "fdc3.instrument", onContext: handleContext });
	useFdc3Channel({
		channelName: CUSTOM_APP_CHANNEL,
		contextType: "fdc3.instrument",
		onContext: handleContext,
	});

	const clearMessage = () => {
		setMessage("");
	};

	return (
		<div className="col fill gap20">
			<header className="row spread middle">
				<div className="col">
					<h1>HERE React View 2</h1>
					<h1 className="tag">React app view in an HERE workspace</h1>
				</div>
				<div className="row middle gap10">
					<img src="logo.svg" alt="HERE" height="40px" />
				</div>
			</header>
			<main className="col gap10 left width-full">
				{message && (
					<>
						<fieldset className="width-full">
							<label htmlFor="message">Context Received</label>
							<pre id="message" className="width-full" style={{ minHeight: "110px" }}>
								{message}
							</pre>
						</fieldset>
						<button type="button" onClick={clearMessage}>
							Clear
						</button>
					</>
				)}
			</main>
		</div>
	);
}
