// frameworks/angular/container/src/app/view2/view2.component.ts
import { ChangeDetectionStrategy, Component, type OnInit, signal } from "@angular/core";

@Component({
	selector: "app-view2",
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [],
	template: `
		<div class="col fill gap20">
			<header class="row spread middle">
				<div class="col">
					<h1>HERE Angular View 2</h1>
					<h1 class="tag">Angular app view in an HERE container</h1>
				</div>
				<div class="row middle gap10">
					<img src="logo.svg" alt="HERE" height="40px" />
				</div>
			</header>
			<main class="col gap10 left width-full">
				@if (message()) {
					<fieldset class="width-full">
						<label htmlFor="message">Context Received</label>
						<pre id="message" class="width-full" style="min-height: 110px">{{ message() }}</pre>
					</fieldset>
					<button (click)="clearMessage()">Clear</button>
				}
			</main>
		</div>
	`,
})
export class View2Component implements OnInit {
	message = signal<string>("");

	ngOnInit(): void {
		this.listenForFDC3Context();
		this.listenForFDC3ContextAppChannel();
	}

	listenForFDC3Context() {
		if (fdc3) {
			fdc3?.addContextListener("fdc3.instrument", (context) => {
				console.log("ContextService: received message", context);
				this.message.set(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	async listenForFDC3ContextAppChannel() {
		if (fdc3) {
			const appChannel = await fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");
			await appChannel.addContextListener((context) => {
				this.message.set(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	clearMessage() {
		this.message.set("");
	}
}

<div class="col fill gap20">
	<header class="row spread middle">
		<div class="col">
			<h1>OpenFin Angular View 2</h1>
			<h1 class="tag">Angular app view in an OpenFin container</h1>
		</div>
		<div class="row middle gap10">
			<img src="../../assets/logo.svg" alt="OpenFin" height="40px" />
		</div>
	</header>
	<main class="col gap10 left width-full">
		<fieldset class="width-full">
			<label htmlFor="message">Context Received</label>
			<pre id="message" class="width-full" style="min-height:110px">{{message}}</pre>
		</fieldset>
		<button (click)="message=''">Clear</button>
	</main>
</div>

// frameworks/react/container/src/views/View2.tsx
import React, { useEffect, useState } from "react";
import logo from "../logo.svg";

function View2() {
	const [message, setMessage] = useState("");

	useEffect(() => {
		(async function () {
			await listenForFDC3Context();
			await listenForFDC3ContextAppChannel();
		})();
	}, []);

	async function listenForFDC3Context() {
		if (fdc3) {
			await fdc3.addContextListener((context) => {
				setMessage(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	async function listenForFDC3ContextAppChannel() {
		if (fdc3) {
			const appChannel = await fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");

			await appChannel.addContextListener((context) => {
				setMessage(JSON.stringify(context, undefined, "  "));
			});
		} else {
			console.error("FDC3 is not available");
		}
	}

	return (
		<div className="col fill gap20">
			<header className="row spread middle">
				<div className="col">
					<h1>OpenFin React View 2</h1>
					<h1 className="tag">React app view in an OpenFin container</h1>
				</div>
				<div className="row middle gap10">
					<img src={logo} alt="OpenFin" height="40px" />
				</div>
			</header>
			<main className="col gap10 left width-full">
				<fieldset className="width-full">
					<label htmlFor="message">Context Received</label>
					<pre id="message" className="width-full" style={{ minHeight: "110px" }}>
						{message}
					</pre>
				</fieldset>
				<button onClick={() => setMessage("")}>Clear</button>
			</main>
		</div>
	);
}

export default View2;
